// <auto-generated />
using System;
using EternalBAND.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EternalBAND.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241226153748_Guid_Added_Inside_Blog_Table")]
    partial class Guid_Added_Inside_Blog_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EternalBAND.DomainObjects.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HtmlText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Contacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Instruments", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instrument = "Gitar",
                            InstrumentShort = "Guitar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Instrument = "Bas Gitar",
                            InstrumentShort = "Bass Guitar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Instrument = "Davul",
                            InstrumentShort = "Drum",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Instrument = "Piano",
                            InstrumentShort = "Piano",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Instrument = "Klavye",
                            InstrumentShort = "Keyboard",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Instrument = "Saksafon",
                            InstrumentShort = "Saxophone",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            Instrument = "Keman",
                            InstrumentShort = "Violin",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            Instrument = "Vokal",
                            InstrumentShort = "Vocal",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            Instrument = "Kontrabas",
                            InstrumentShort = "Kontrabas",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.MessageBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPostDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("PostIdBackup")
                        .HasColumnType("int");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("MessageBoxes");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageBoxId")
                        .HasColumnType("int");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RelatedPostId")
                        .HasColumnType("int");

                    b.Property<string>("SenderUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MessageBoxId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("ReceiveUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RedirectLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedElementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiveUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.PostTypes", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilterText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCreateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AddedDate = new DateTime(2024, 3, 3, 0, 16, 0, 0, DateTimeKind.Unspecified),
                            FilterText = "Grup Arıyorum",
                            PostCreateText = "Grup Arıyorum",
                            Type = "Group",
                            TypeText = "Grup İlanları"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            AddedDate = new DateTime(2024, 3, 3, 0, 16, 0, 0, DateTimeKind.Unspecified),
                            FilterText = "Müzisyen Arıyorum",
                            PostCreateText = "Müzisyen Arıyorum",
                            Type = "Musician",
                            TypeText = "Müzisyen İlanları"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            AddedDate = new DateTime(2024, 3, 3, 0, 16, 0, 0, DateTimeKind.Unspecified),
                            FilterText = "Ders Almak İstiyorum",
                            PostCreateText = "Ders Vermek İstiyorum",
                            Type = "Lesson",
                            TypeText = "Ders İlanları"
                        });
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AdminConfirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AdminConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminConfirmationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HTMLText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstrumentsId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Photo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostTypesId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("SeoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("AdminConfirmationUserId");

                    b.HasIndex("InstrumentsId");

                    b.HasIndex("PostTypesId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.UserProfileControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsersId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("UserProfileControl");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "13362109-dc20-49ad-8b05-db533707a22f",
                            AccessFailedCount = 0,
                            Age = 0,
                            City = 0,
                            ConcurrencyStamp = "6816aac2-3448-47e9-bdbc-54c8a347c8d4",
                            Email = "admin.engin@bandbul.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN.ENGIN@BANDBUL.COM",
                            NormalizedUserName = "ADMIN.ENGIN@BANDBUL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGSxNCu4wMt6kEDKflsB4iDuKt2yS7sT6hJkDPGcErKguUVkZfUrVAfG9k5fJ0UmWg==",
                            PhoneNumber = "5000000000",
                            PhoneNumberConfirmed = false,
                            PhotoPath = "/images/user_photo/profile.png",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ce732604-2c07-4228-825d-6e49abb26ef3",
                            Surname = "",
                            TwoFactorEnabled = false,
                            UserName = "admin.engin@bandbul.com"
                        },
                        new
                        {
                            Id = "d15a305f-ca73-4417-9143-4c3c0628e88d",
                            AccessFailedCount = 0,
                            Age = 0,
                            City = 0,
                            ConcurrencyStamp = "6816aac2-3448-47e9-bdbc-54c8a347c8d4",
                            Email = "admin.berkay@bandbul.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN.BERKAY@BANDBUL.COM",
                            NormalizedUserName = "ADMIN.BERKAY@BANDBUL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+AcmaaI8WodUj1b5Xy1b5+hqiuMgKZZ3p9wYV9zLYYgH5a1iFjTtDrLEItiOEbXg==",
                            PhoneNumber = "5000000000",
                            PhoneNumberConfirmed = false,
                            PhotoPath = "/images/user_photo/profile.png",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ce732604-2c07-4228-825d-6e49abb26ef3",
                            Surname = "",
                            TwoFactorEnabled = false,
                            UserName = "admin.berkay@bandbul.com"
                        },
                        new
                        {
                            Id = "93816595-56df-4287-b5f1-1a9d36871222",
                            AccessFailedCount = 0,
                            Age = 0,
                            City = 0,
                            ConcurrencyStamp = "6816aac2-3448-47e9-bdbc-54c8a347c8d4",
                            Email = "admin.enis@bandbul.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN.ENIS@BANDBUL.COM",
                            NormalizedUserName = "ADMIN.ENIS@BANDBUL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGO/WArxg5ovBMlRGIQnnEEfmuvZHhPq2g7hS2WSnZzD1kIUxYCremYES+B1wY4uHg==",
                            PhoneNumber = "5000000000",
                            PhoneNumberConfirmed = false,
                            PhotoPath = "/images/user_photo/profile.png",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ce732604-2c07-4228-825d-6e49abb26ef3",
                            Surname = "",
                            TwoFactorEnabled = false,
                            UserName = "admin.enis@bandbul.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "39d321fc-0911-4412-a19e-98fb7d068440",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a3641119-ff91-4eca-aa32-120c36d61d1a",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "13362109-dc20-49ad-8b05-db533707a22f",
                            RoleId = "39d321fc-0911-4412-a19e-98fb7d068440"
                        },
                        new
                        {
                            UserId = "d15a305f-ca73-4417-9143-4c3c0628e88d",
                            RoleId = "39d321fc-0911-4412-a19e-98fb7d068440"
                        },
                        new
                        {
                            UserId = "93816595-56df-4287-b5f1-1a9d36871222",
                            RoleId = "39d321fc-0911-4412-a19e-98fb7d068440"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.MessageBox", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Posts", "Post")
                        .WithMany("MessageBoxes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Messages", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.MessageBox", "MessageBox")
                        .WithMany("Messages")
                        .HasForeignKey("MessageBoxId");

                    b.HasOne("EternalBAND.DomainObjects.Users", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId");

                    b.HasOne("EternalBAND.DomainObjects.Users", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId");

                    b.Navigation("MessageBox");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Notification", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", "ReceiveUser")
                        .WithMany()
                        .HasForeignKey("ReceiveUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EternalBAND.DomainObjects.Users", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId");

                    b.Navigation("ReceiveUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Posts", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId");

                    b.HasOne("EternalBAND.DomainObjects.Users", "AdminConfirmationUser")
                        .WithMany()
                        .HasForeignKey("AdminConfirmationUserId");

                    b.HasOne("EternalBAND.DomainObjects.Instruments", "Instruments")
                        .WithMany()
                        .HasForeignKey("InstrumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EternalBAND.DomainObjects.PostTypes", "PostTypes")
                        .WithMany()
                        .HasForeignKey("PostTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("AdminConfirmationUser");

                    b.Navigation("Instruments");

                    b.Navigation("PostTypes");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.UserProfileControl", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EternalBAND.DomainObjects.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EternalBAND.DomainObjects.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.MessageBox", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EternalBAND.DomainObjects.Posts", b =>
                {
                    b.Navigation("MessageBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
