name: Increment Patch Version

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  increment_patch_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Current Version
        id: read-version
        run: |
          # Read the current version from AssemblyInfo.cs and store it as an output
          current_version=$(awk -F '"' '/AssemblyVersion/ {print $2}' YourProject/Properties/AssemblyInfo.cs)
          echo "::set-output name=current_version::$current_version"

      - name: Increment Patch Version
        id: increment-patch-version
        run: |
          # Increment the patch component of the version
          current_version="${{ steps.read-version.outputs.current_version }}"
          IFS='.' read -ra version_components <<< "$current_version"
          major="${version_components[0]}"
          minor="${version_components[1]}"
          patch="${version_components[2]}"
          revision="${version_components[3]}"
          ((revision++))
          incremented_version="$major.$minor.$patch.$revision"
          echo "::set-output name=incremented_version::$incremented_version"

      - name: Get Current Branch Name
        id: branch-name
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
        
      - name: Update AssemblyInfo.cs
        run: |
          # Update the AssemblyInfo.cs file with the incremented patch version
          incremented_version="${{ steps.increment-patch-version.outputs.incremented_version }}"
          branch_name="${{ steps.branch-name.outputs.branch_name }}"
          sed -i "s/\[assembly: AssemblyMetadata(\"Git.BranchName\", \"\")]/[assembly: AssemblyMetadata(\"Git.BranchName\", \"$branch_name\")]/" YourProject/Properties/AssemblyInfo.cs
          sed -i "s/\[assembly: AssemblyVersion(\".*\"\)\]/[assembly: AssemblyVersion(\"$incremented_version\")]/" Band/Properties/AssemblyInfo.cs
          sed -i "s/\[assembly: AssemblyFileVersion(\".*\"\)\]/[assembly: AssemblyFileVersion(\"$incremented_version\")]/" Band/Properties/AssemblyInfo.cs

      - name: Commit and Push Version Update
        run: |
          # git config user.name "Your Git Username"
          # git config user.email "your@email.com"
          git add Band/Properties/AssemblyInfo.cs
          git commit -m "Bump patch version to ${{ steps.increment-patch-version.outputs.incremented_version }}" --no-verify
          git push origin HEAD